refactor: move AD app Reader permissions to AZ config mod
lacework/terraform-azure-config pull request #29
Opened 2021-10-08 16:14 UTC by marcosgm

---
name: Refactoring code to allow (optional) unbundling 
about: 'bug(#28)  Move this code from the AD Application Module to the Azure Config Module'
---
As part of code refactoring which is pre-requisite for new Azure AD permissions using MSGraph

2021-10-11 09:21 UTC, afiune requested changes

2021-10-11 09:21 UTC, afiune commented on main.tf
> +  service_principal_id = var.use_existing_ad_application ? var.service_principal_id : module.az_cfg_ad_application.service_principal_id
since we created this local variable, we need to update our outputs https://github.com/lacework/terraform-azure-config/blob/main/output.tf#L12-L15

2021-10-11 09:21 UTC, afiune commented on main.tf
> +  tenant_id = length(var.tenant_id) > 0 ? var.tenant_id : data.azurerm_subscription.primary.tenant_id
We must update this output: https://github.com/lacework/terraform-azure-config/blob/main/output.tf#L17-L20

2021-10-12 18:58 UTC, marcosgm commented on main.tf
> +  role_definition_name = "Key Vault Reader"
yes, so we can support the 2 kind of permissions for Keyvault: one uses Access Policy (which we had in TF already), the new one uses Azure AD RBAC (hence this new role)

2021-10-12 19:13 UTC, marcosgm commented on variables.tf
> +  description = "The Service Principal id to use. Required when `use_existing_ad_application` is set to `true`"
done

2021-10-13 20:40 UTC, marcosgm commented
this PR must be released as v1.0

2021-10-15 17:02 UTC, closed without merging